#!/bin/bash

# configuration
export exec_as_user=1000
export exec_as_group=1000
export service_check_path=""
export service_check_tcponly=false

function runsvc(){

    service_name=$1
    service_image=$2

    mkdir -p ~/workspaces/ai/slop/
    mkdir -p ~/workspaces/ai/home/claude
    mkdir -p ~/workspaces/ai/home/codex
    mkdir -p ~/workspaces/ai/home/copilot
    mkdir -p ~/workspaces/ai/home/opencode
    mkdir -p ~/workspaces/ai/home/hermes

    docker run -d \
        --name "${service_name}" \
        --hostname "${service_name}" \
        --restart unless-stopped \
        --user "${exec_as_user}:${exec_as_group}" \
        --network ${DOCKER_NETWORK_NAME} \
        -e "ENV_VAR=VALUE" \
        -v "${DATA_ROOT_FOLDER}/${service_name}/config:/config:ro" \
        -v "${DATA_ROOT_FOLDER}/${service_name}/data:/data:rw" \
        -v ~/workspaces/ai/slop/:/home/user/slop \
        -v ~/workspaces/ai/home/claude:/home/user/.claude \
        -v ~/workspaces/ai/home/codex:/home/user/.codex \
        -v ~/workspaces/ai/home/copilot/:/home/user/.copilot \
        -v ~/workspaces/ai/home/opencode/:/home/user/.opencode \
        -v ~/workspaces/ai/home/hermes:/home/user/.hermes \
        -l "traefik.enable=true" \
        -l "traefik.http.services.${service_name}.loadbalancer.server.port=8123" \
        -l "traefik.http.services.${service_name}.loadbalancer.server.scheme=http" \
        -l "traefik.http.routers.${service_name}.service=${service_name}" \
        -l "traefik.http.routers.${service_name}.entrypoints=https" \
        -l "traefik.http.routers.${service_name}.tls=true" \
        -l "traefik.http.routers.${service_name}.rule=Host(\`${service_name}.${WILDCARD_DOMAIN}\`)" \
        -p "${EXPOSE_BINDADDRESS}:8123:8123" \
        ${service_image} \
        aisandbox sleep infinity
    
}

function post_start_tasks(){
    
    service_name=$1

    # Add any post-start tasks here
    return 0
}
