#!/bin/bash

# configuration
export exec_as_user=0
export exec_as_group=0
export service_check_path=":5000"
export service_check_tcponly=false

function runsvc(){

    service_name=$1
    service_image=$2

    docker run -d \
        --name "${service_name}" \
        --hostname "${service_name}" \
        --restart unless-stopped \
        --user "${exec_as_user}:${exec_as_group}" \
        --network ${DOCKER_NETWORK_NAME} \
        --shm-size="256MB" \
        -e "ENV_VAR=VALUE" \
        -v "${DATA_ROOT_FOLDER}/${service_name}/config:/config:rw" \
        -v "${DATA_ROOT_FOLDER}/${service_name}/data:/media/frigate:rw" \
        -v "/tmp/frigate/cache:/tmp/cache:rw" \
        -l "traefik.enable=true" \
        -l "traefik.http.services.${service_name}.loadbalancer.server.port=5000" \
        -l "traefik.http.services.${service_name}.loadbalancer.server.scheme=http" \
        -l "traefik.http.routers.${service_name}.service=${service_name}" \
        -l "traefik.http.routers.${service_name}.entrypoints=https" \
        -l "traefik.http.routers.${service_name}.tls=true" \
        -l "traefik.http.routers.${service_name}.rule=Host(\`${service_name}.${WILDCARD_DOMAIN}\`)" \
        -p "${EXPOSE_BINDADDRESS}:28003:5000" \
        -p "${EXPOSE_BINDADDRESS}:8554:8554" \
        -p "${EXPOSE_BINDADDRESS}:8555:8555" \
        ${service_image}
    
}

function post_start_tasks(){
    
    service_name=$1

    # Add any post-start tasks here
    return 0
}
