#!/bin/bash

# configuration
export exec_as_user=0
export exec_as_group=0
export service_check_path=":6443"
export service_check_tcponly=true

function runsvc(){

    service_name=$1
    service_image=$2

    docker run -d \
        --name "${service_name}" \
	    --privileged \
        --hostname "${service_name}" \
        --restart unless-stopped \
        --user "${exec_as_user}:${exec_as_group}" \
        --network ${DOCKER_NETWORK_NAME} \
        -e "K3S_KUBECONFIG_MODE="644"" \
        -v "${DATA_ROOT_FOLDER}/${service_name}/data/var/lib/rancher/k3s:/var/lib/rancher/k3s:rw" \
        -v "${DATA_ROOT_FOLDER}/${service_name}/data/etc/rancher/k3s:/etc/rancher/k3s:rw" \
        -l "traefik.enable=true" \
        -l "traefik.http.services.${service_name}.loadbalancer.server.port=6443" \
        -l "traefik.http.services.${service_name}.loadbalancer.server.scheme=https" \
        -l "traefik.http.routers.${service_name}.service=${service_name}" \
        -l "traefik.http.routers.${service_name}.entrypoints=https" \
        -l "traefik.http.routers.${service_name}.tls=true" \
        -l "traefik.http.routers.${service_name}.rule=Host(\`${service_name}.${WILDCARD_DOMAIN}\`)" \
        -l "traefik.http.routers.${service_name}-k3s.rule=HostRegexp(\`.*\.${K3S_WILDCARD_DOMAIN}\`)" \
        -l "traefik.http.routers.${service_name}-k3s.entrypoints=https" \
        -l "traefik.http.routers.${service_name}-k3s.tls=true" \
        -l "traefik.http.routers.${service_name}-k3s.service=${service_name}-k3s" \
        -l "traefik.http.services.${service_name}-k3s.loadbalancer.server.port=443" \
        -l "traefik.http.services.${service_name}-k3s.loadbalancer.server.scheme=https" \
-p "${EXPOSE_BINDADDRESS}:6443:6443" \
        ${service_image} \
        server --disable=servicelb,traefik --tls-san 172.18.0.1 --tls-san ${service_name}.${WILDCARD_DOMAIN}
    
}

function post_start_tasks(){
    
    service_name=$1
    mkdir -p ~/.kube
    cp ${DATA_ROOT_FOLDER}/${service_name}/data/etc/rancher/k3s/k3s.yaml ~/.kube/config
    K8S_PUBLIC_DOMAIN=${service_name}.${WILDCARD_DOMAIN}
    OLD_CLUSTER=$(kubectl config view --kubeconfig ~/.kube/config -o jsonpath='{.clusters[0].name}')
    OLD_CONTEXT=$(kubectl config view --kubeconfig ~/.kube/config -o jsonpath='{.contexts[0].name}')
    sed -i "s|server: https://.*|server: https://$K8S_PUBLIC_DOMAIN:6443|g" ~/.kube/config
    sed -i "/^clusters:/,/^contexts:/s|name: $OLD_CLUSTER$|name: $K8S_PUBLIC_DOMAIN|" ~/.kube/config
    sed -i "s|cluster: $OLD_CLUSTER$|cluster: $K8S_PUBLIC_DOMAIN|g" ~/.kube/config
    kubectl config rename-context "$OLD_CONTEXT" "$K8S_PUBLIC_DOMAIN" --kubeconfig ~/.kube/config
    return 0
}
