#!/bin/bash

# configuration
export exec_as_user=1000
export exec_as_group=1000
export service_check_path=":8081/actuator/health"
export service_check_tcponly=false

function runsvc(){

    service_name=$1
    service_image=$2

    mkdir -p "${DATA_ROOT_FOLDER}/media-content"

    docker run -d \
        --name "${service_name}" \
        --hostname "${service_name}" \
        --restart unless-stopped \
        --user "${exec_as_user}:${exec_as_group}" \
        --network ${DOCKER_NETWORK_NAME} \
        -e "OTEL_JAVAAGENT_ENABLED=false" \
        -e "VIDEOS_FOLDER=/media-content/p01/videos" \
        -e "MUSIC_FOLDER=/media-content/p01/music" \
        -e "SHOWS_FOLDER=/media-content/p01/shows" \
        -e "MOVIES_FOLDER=/media-content/p01/movies" \
        -e "KARAOKE_FOLDER=/media-content/p01/karaoke" \
        -v "${DATA_ROOT_FOLDER}/media-content:/media-content:rw" \
        -l "traefik.enable=true" \
        -l "traefik.http.services.${service_name}.loadbalancer.server.port=8080" \
        -l "traefik.http.services.${service_name}.loadbalancer.server.scheme=http" \
        -l "traefik.http.routers.${service_name}.service=${service_name}" \
        -l "traefik.http.routers.${service_name}.entrypoints=http" \
        -l "traefik.http.routers.${service_name}.tls=false" \
        -l "traefik.http.routers.${service_name}.rule=Host(\`${service_name}.${WILDCARD_DOMAIN}\`)" \
        -p "${EXPOSE_BINDADDRESS}:28006:8080" \
        ${service_image}
    
}

function post_start_tasks(){
    # Add any post-start tasks here
    service_name=$1
    
    return 0
}
