#!/bin/bash

# configuration
export exec_as_user=1000
export exec_as_group=1000
export service_check_path=":8081/actuator/health"
export service_check_tcponly=false

function runsvc(){

    service_name=$1
    service_image=$2

    docker run -d \
        --name "${service_name}" \
        --hostname "${service_name}" \
        --restart unless-stopped \
        --user "${exec_as_user}:${exec_as_group}" \
        --network ${DOCKER_NETWORK_NAME} \
        -e "OTEL_JAVAAGENT_ENABLED=false" \
        -e "DATA_FILE_PATH=/data/data.json" \
        -v "${DATA_ROOT_FOLDER}/${service_name}/data:/data:rw" \
        -l "traefik.enable=true" \
        -l "traefik.http.services.${service_name}.loadbalancer.server.port=8080" \
        -l "traefik.http.services.${service_name}.loadbalancer.server.scheme=http" \
        -l "traefik.http.routers.${service_name}.service=${service_name}" \
        -l "traefik.http.routers.${service_name}.entrypoints=https" \
        -l "traefik.http.routers.${service_name}.tls=true" \
        -l "traefik.http.routers.${service_name}.rule=Host(\`${service_name}.${WILDCARD_DOMAIN}\`)" \
        -p "${EXPOSE_BINDADDRESS}:28005:8080" \
        ${service_image}
    
}

function post_start_tasks(){
    
    service_name=$1

    # Add any post-start tasks here
    return 0
}
