#!/bin/bash

# configuration
export exec_as_user=0
export exec_as_group=0
export service_check_path=":81"
export service_check_tcponly=false

function runsvc(){

    service_name=$1
    service_image=$2

    mkdir -p "${DATA_ROOT_FOLDER}/${service_name}/data/db"
    mkdir -p "${DATA_ROOT_FOLDER}/${service_name}/data/tls"

    docker run -d \
        --name "${service_name}" \
        --hostname "${service_name}" \
        --restart unless-stopped \
        --user "${exec_as_user}:${exec_as_group}" \
        --network ${DOCKER_NETWORK_NAME} \
        -e "ENV_VAR=VALUE" \
        -v "${DATA_ROOT_FOLDER}/${service_name}/config:/config:ro" \
        -v "${DATA_ROOT_FOLDER}/${service_name}/data/db:/data:rw" \
        -v "${DATA_ROOT_FOLDER}/${service_name}/data/tls:/etc/letsencrypt:rw" \
        -l "traefik.enable=true" \
        -l "traefik.http.services.${service_name}.loadbalancer.server.port=81" \
        -l "traefik.http.services.${service_name}.loadbalancer.server.scheme=http" \
        -l "traefik.http.routers.${service_name}.service=${service_name}" \
        -l "traefik.http.routers.${service_name}.entrypoints=https" \
        -l "traefik.http.routers.${service_name}.tls=true" \
        -l "traefik.http.routers.${service_name}.rule=Host(\`${service_name}.${WILDCARD_DOMAIN}\`)" \
        -p "${EXPOSE_BINDADDRESS}:81:81" \
        -p "${EXPOSE_BINDADDRESS}:28443:443" \
        ${service_image}
    
}

function post_start_tasks(){
    
    service_name=$1

    # Add any post-start tasks here
    return 0
}
