#!/bin/bash

# configuration
export exec_as_user=1000
export exec_as_group=1000
export service_check_path=":8384/"
export service_check_tcponly=false

function runsvc(){

    folders="
        /home/$TARGET_USERNAME/.config/retroarch/saves
        /home/$TARGET_USERNAME/.config/retroarch/states
        /home/$TARGET_USERNAME/.config/PCSX2/memcards
        /home/$TARGET_USERNAME/.config/PCSX2/sstates
        /home/$TARGET_USERNAME/.config/PCSX2/covers
        /home/$TARGET_USERNAME/ES-DE/downloaded_media
        /home/$TARGET_USERNAME/.local/share/Cemu/mlc01
        /home/$TARGET_USERNAME/.local/share/dolphin-emu/GC
        /home/$TARGET_USERNAME/.local/share/dolphin-emu/Wii
    "

    for folder in $(echo $folders); do
        mkdir -p "$folder"
    done

    service_name=$1
    service_image=$2


    docker run -d \
        --name "${service_name}" \
        --hostname "${service_name}" \
        --restart unless-stopped \
        --network ${DOCKER_NETWORK_NAME} \
        -e PUID=${exec_as_user} \
        -e PGID=${exec_as_group} \
        -e TZ=Europe/Paris \
        -v "${DATA_ROOT_FOLDER}/${service_name}/data:/var/syncthing/config:rw" \
        -v "/home/$TARGET_USERNAME/.config/retroarch/saves:/var/syncthing/saves:rw" \
        -v "/home/$TARGET_USERNAME/.config/retroarch/states:/var/syncthing/states:rw" \
        -v "/home/$TARGET_USERNAME/.config/PCSX2/memcards:/var/syncthing/PCSX2/memcards:rw" \
        -v "/home/$TARGET_USERNAME/.config/PCSX2/sstates:/var/syncthing/PCSX2/sstates:rw" \
        -v "/home/$TARGET_USERNAME/.config/PCSX2/covers:/var/syncthing/PCSX2/covers:rw" \
        -v "/home/$TARGET_USERNAME/ES-DE/downloaded_media:/var/syncthing/downloaded_media:rw" \
        -v "/home/$TARGET_USERNAME/.local/share/dolphin-emu/GC:/var/syncthing/GC:rw" \
        -v "/home/$TARGET_USERNAME/.local/share/dolphin-emu/Wii:/var/syncthing/Wii:rw" \
        -v "/home/$TARGET_USERNAME/.local/share/Cemu/mlc01:/var/syncthing/cemu:rw" \
        -l "traefik.enable=true" \
        -l "traefik.http.services.${service_name}.loadbalancer.server.port=8384" \
        -l "traefik.http.services.${service_name}.loadbalancer.server.scheme=http" \
        -l "traefik.http.routers.${service_name}.service=${service_name}" \
        -l "traefik.http.routers.${service_name}.entrypoints=https" \
        -l "traefik.http.routers.${service_name}.tls=true" \
        -l "traefik.http.routers.${service_name}.rule=Host(\`${service_name}.${WILDCARD_DOMAIN}\`)" \
        -p "${EXPOSE_BINDADDRESS}:8384:8384" \
        -p "22000:22000" \
        ${service_image}
    
}

function post_start_tasks(){
    
    service_name=$1

    # Add any post-start tasks here
    return 0
}
