#!/bin/bash

# configuration
export exec_as_user=0
export exec_as_group=0
export service_check_path=""
export service_check_tcponly=false

function runsvc(){

    service_name=$1
    service_image=$2

    docker run -d \
        --name "${service_name}" \
	--privileged \
        --hostname "${service_name}" \
        --restart unless-stopped \
        --user "${exec_as_user}:${exec_as_group}" \
        --network ${DOCKER_NETWORK_NAME} \
        -v "${DATA_ROOT_FOLDER}/${service_name}/data:/data:rw" \
        -l "traefik.enable=false" \
        ${service_image} \
        /bin/bash -c "sleep infinity"
}

function post_start_tasks(){
    
    service_name=$1

    # Add any post-start tasks here
    return 0
}
