#!/bin/bash

# configuration
export exec_as_user=1000
export exec_as_group=1000
export service_check_path=""
export service_check_tcponly=true

function runsvc(){

    service_name=$1
    service_image=$2

    nbpeers=71
    peers=""
    for i in $(seq 2 $nbpeers); do
        if [ -n "$peers" ]; then peers+=","; fi
        peers+="p${i}"
    done
    echo $peers

    peersmapping=(
        # servers
        "p2|aaon"
        # pcs
        "p20|lpro"
        "p21|lg15"
        "p22|mbm1"
        # phones & tablets
        "p40|iphone 8s quang"
        "p41|ipad air quang"
        "p42|ipad a16 quang"
        "p43|thomson quang"
        "p44|ipad 9 max"
        "p45|iphone 14 pro max hoa"
    )

    for entry in "${peersmapping[@]}"; do
        peernb="${entry%%|*}"
        name="${entry#*|}"
    echo $peernb "->" $name
    done


    docker run -d \
        --name "${service_name}" \
        --hostname "${service_name}" \
        --restart unless-stopped \
        --network ${DOCKER_NETWORK_NAME} \
        --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
        --cap-add=NET_ADMIN \
        --cap-add=SYS_MODULE \
        -e PUID=${exec_as_user} \
        -e PGID=${exec_as_group} \
        -e TZ=Europe/Paris \
        -e SERVERURL=waaon.dns.army \
        -e SERVERPORT=53921 \
        -e PEERS=$peers \
        -e PEERDNS="none" \
        -e INTERNAL_SUBNET=10.13.13.0 \
        -e ALLOWEDIPS=10.13.13.0/24 \
        -e PERSISTENTKEEPALIVE_PEERS=all \
        -e LOG_CONFS=true \
        -v "${DATA_ROOT_FOLDER}/${service_name}/data:/config:rw" \
        -v /lib/modules:/lib/modules:ro \
        -l "traefik.enable=false" \
        -p 53921:51820/udp \
        ${service_image} \
    
}

function post_start_tasks(){
    
    service_name=$1

    
    

    return 0
}
