{
 "title": "Docker logs",
 "tags": [ "docker-integration" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values({job!=\"kubelet\", namespace=\"\" ,container!=\"\"}, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values({job!=\"kubelet\", namespace=\"\" ,container!=\"\",job=~\"$job\"}, instance)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values({job!=\"kubelet\", namespace=\"\" ,container!=\"\",job=~\"$job\",instance=~\"$instance\"}, container)"
   },
   { "name": "regex_search", "label": "Regex search" }
  ]
 },
 "panels": [
  { "title": "Integration Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Logs",
   "type": "stat",
   "description": "Shows if logs are being received for the selected time range.",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=~\"$job\"}[$__auto]))\n"
    }
   ]
  },
  {
   "title": "Latest logs received",
   "type": "stat",
   "description": "Shows the timestamp of the latest logs received for this integration in the last 24 hours.",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=~\"$job\"}[$__auto]))\n"
    }
   ]
  },
  {
   "title": "Integration version",
   "type": "text",
   "description": "Shows the installed version of this integration.",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "options": {
    "content": "<p style=\"text-align: center\">1.3.4</p>"
   }
  },
  {
   "title": "Logs volume",
   "type": "timeseries",
   "description": "Logs volume grouped by \"container\" label.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (container) (count_over_time({job!=\"kubelet\", namespace=\"\" ,container!=\"\",job=~\"$job\",instance=~\"$instance\",container=~\"$container\"}\n|~ \"$regex_search\"\n\n[$__auto]))\n",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "{job!=\"kubelet\", namespace=\"\" ,container!=\"\",job=~\"$job\",instance=~\"$instance\",container=~\"$container\"} \n|~ \"$regex_search\"\n\n| label_format timestamp=\"{{__timestamp__}}\"\n| line_format `{{ if eq \"[[instance]]\" \".*\" }}{{alignLeft 25 .instance}}|{{ alignLeft 25 .container }}|{{else}}{{ alignLeft 25 .container}}|{{end}} {{__line__}}`\n\n"
    }
   ]
  }
 ]
}